# Generated by Django 4.2.2 on 2023-06-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='friend_convo',
            new_name='friend',
        ),
    ]
