# Generated by Django 4.2.2 on 2023-07-02 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_friendlist_alter_conversation_friend_delete_friend'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendList',
            new_name='Friend',
        ),
        migrations.AlterModelOptions(
            name='friend',
            options={'verbose_name_plural': 'Friend'},
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='friend',
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
